name: OrangeFox - Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup Space
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /opt/ghc
        sudo apt clean

    - name: Install Build Tools
      run: |
        sudo apt update
        sudo apt install -y bc build-essential git-core gnupg gperf libsdl1.2-dev libesd0-dev libwxgtk3.0-gtk3-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-8-jdk gcc-multilib g++-multilib x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python

    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync OrangeFox Sources
      run: |
        mkdir ~/fox
        cd ~/fox
        repo init --depth=1 -u https://gitlab.com/OrangeFox/Manifest.git -b fox_11.0
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        # Клонируем твое дерево из правильного репозитория и ветки
        git clone https://github.com/uratsakidogi1488/android_device_wheatek_WP15 -b WP15_RU-user-11-RP1A.200720.011-1653633312-release-keys ~/fox/device/wheatek/WP15

    - name: Build OrangeFox
      run: |
        cd ~/fox
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        # Используем конфиг из твоего AndroidProducts.mk
        lunch omni_WP15-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-WP15
        path: ~/fox/out/target/product/WP15/*.img
        
