name: OrangeFox - Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup Space
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /opt/ghc
        sudo apt clean

    - name: Install Build Tools
      run: |
        sudo apt update
        sudo apt install -y bc build-essential git-core gnupg gperf libsdl1.2-dev squashfs-tools zip curl libncurses5-dev zlib1g-dev openjdk-8-jdk gcc-multilib g++-multilib x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python3 python-is-python3

    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
     
    - name: Sync OrangeFox Sources
      run: |
        rm -rf ~/fox
        mkdir -p ~/fox/bootable/recovery
        mkdir -p ~/fox/vendor/recovery
        cd ~/fox
        git clone --depth=1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OrangeFoxRecovery/recovery.git -b fox_11.0 bootable/recovery
        if ! git clone --depth=1 https://gitlab.com/OrangeFox/vendor.git -b fox_11.0 vendor/recovery 2>&1; then
        echo "Не удалось клонировать из GitLab. Проверьте:"
        echo "1. Доступность URL: https://gitlab.com/OrangeFox/vendor.git"
        echo "2. Существование ветки fox_11.0"
        echo "3. Права доступа к приватному репозиторию"
        exit 1
    
    - name: Clone Device Tree
      run: |
        git clone https://github.com/uratsakidogi1488/android_device_wheatek_WP15 ~/fox/device/wheatek/WP15
        
  
    - name: Create Config File
      run: |
        cd ~/fox/device/wheatek/WP15
        echo "def check_config(config):" > fox.config.py
        echo "    config['FOX_VERSION'] = 'R11.1'" >> fox.config.py
        echo "    config['FOX_BUILD_TYPE'] = 'Unofficial'" >> fox.config.py
        
    - name: Build OrangeFox
      run: |
        cd ~/fox
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch omni_WP15-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-WP15
        path: ~/fox/out/target/product/WP15/*.img
        
